"""Turn the sprite SVGs in plugin/assets into the modules the mod imports.

    python3 scripts/build-sprites.py

- plugin/hooks/meatball.ts: the 32x32 sprite as SVG markup, for the desktop app.

(plugin/assets/meatball-16.svg, the 16x16 sprite, isn't built into the mod: in a
terminal he is one line of text.)
"""

import json

ASSETS = 'plugin/assets'
HOOKS = 'plugin/hooks'


def big():
    svg = open(f'{ASSETS}/meatball.svg').read().strip()
    with open(f'{HOOKS}/meatball.ts', 'w') as out:
        out.write(
            '// Generated by scripts/build-sprites.py from plugin/assets/meatball.svg: the sprite.\n'
            '// Its root attributes pick the pose: data-fill (normal/full/stuffed), data-mood\n'
            '// (alert/hurt/sleep/busy), data-chomp, data-mouth, data-idle and data-roll.\n'
            f'export const MEATBALL = {json.dumps(svg)}\n'
        )


if __name__ == '__main__':
    big()
    print('built plugin/hooks/meatball.ts')
