"""Turn the sprite SVGs in plugin/assets into the modules the mod imports.

    python3 scripts/build-sprites.py

- plugin/hooks/meatball.ts: the 32x32 sprite as SVG markup, for the desktop app.
- plugin/hooks/sprite16.ts: the 16x16 sprite as a tree of classed groups and
  pixel rects, for the terminal, which paints it itself in half-block cells.
"""

import json
import re
import xml.etree.ElementTree as ET

ASSETS = 'plugin/assets'
HOOKS = 'plugin/hooks'


def big():
    svg = open(f'{ASSETS}/meatball.svg').read().strip()
    with open(f'{HOOKS}/meatball.ts', 'w') as out:
        out.write(
            '// Generated by scripts/build-sprites.py from plugin/assets/meatball.svg: the sprite.\n'
            '// Its root attributes pick the pose: data-fill (normal/full/stuffed), data-mood\n'
            '// (alert/hurt/sleep/busy), data-chomp, data-mouth, data-idle and data-roll.\n'
            f'export const MEATBALL = {json.dumps(svg)}\n'
        )


def node(element):
    """A group as {c: classes, r: [x, y, w, h, color, ...], k: children}."""
    out = {}
    classes = element.attrib.get('class', '').split()
    if classes:
        out['c'] = classes
    rects, kids = [], []
    for child in element:
        tag = child.tag.split('}')[1]
        if tag == 'rect':
            a = child.attrib
            rects += [int(a['x']), int(a['y']), int(a['width']), int(a['height']), int(a['fill'].lstrip('#'), 16)]
        elif tag == 'g':
            kids.append(node(child))
    if rects:
        out['r'] = rects
    if kids:
        out['k'] = kids
    return out


def small():
    svg = re.sub(r'<style>.*?</style>', '', open(f'{ASSETS}/meatball-16.svg').read(), flags=re.S)
    tree = node(ET.fromstring(svg))
    with open(f'{HOOKS}/sprite16.ts', 'w') as out:
        out.write(
            '// Generated by scripts/build-sprites.py from plugin/assets/meatball-16.svg: the 16x16\n'
            '// sprite for the terminal. Each group carries its classes (c), its pixel rects as\n'
            '// flat [x, y, w, h, 0xRRGGBB] runs (r), and its child groups (k).\n'
            'export type SpriteNode = { c?: string[]; r?: number[]; k?: SpriteNode[] }\n\n'
            f'export const SPRITE16: SpriteNode = {json.dumps(tree, separators=(",", ":"))}\n'
        )


if __name__ == '__main__':
    big()
    small()
    print('built plugin/hooks/meatball.ts and plugin/hooks/sprite16.ts')
