"""Turn the sprite SVGs in plugin/assets into the modules the mod imports.

    python3 scripts/build-sprites.py

- plugin/hooks/meatball.ts: the 32x32 sprite and the agents strip (up to four
  mini meatballs) as SVG markup, for the desktop app.

(plugin/assets/meatball-16.svg, the 16x16 sprite, isn't built into the mod: in a
terminal he is one line of text.)
"""

import json
import re
import xml.etree.ElementTree as ET

SVG_NS = 'http://www.w3.org/2000/svg'
ET.register_namespace('', SVG_NS)

ASSETS = 'plugin/assets'
HOOKS = 'plugin/hooks'


def compact(svg):
    """The same picture in fewer bytes: runs of same-colored pixel rects become one path.

    Only neighbours in document order are merged, so paint order (and any
    overlap) is unchanged. The desktop takes at most 128KB of SVG.
    """
    style = re.search(r'<style>.*?</style>', svg, re.S).group(0)
    root = ET.fromstring(svg.replace(style, '<style/>'))
    rect = f'{{{SVG_NS}}}rect'

    def walk(group):
        children = list(group)
        for child in children:
            group.remove(child)
        run_fill, run = None, []

        def flush():
            if run:
                path = ET.Element(f'{{{SVG_NS}}}path', {'d': ''.join(run)})
                if run_fill:
                    path.set('fill', run_fill)
                group.append(path)

        for child in children:
            if child.tag == rect:
                a = child.attrib
                fill = a.get('fill', '')
                if fill != run_fill:
                    flush()
                    run_fill, run = fill, []
                run.append(f"M{a['x']} {a['y']}h{a['width']}v{a['height']}h-{a['width']}z")
            else:
                flush()
                run_fill, run = None, []
                walk(child)
                group.append(child)
        flush()

    walk(root)
    out = ET.tostring(root, encoding='unicode', short_empty_elements=True)
    return out.replace('<style />', style, 1)

def big():
    svg = compact(open(f'{ASSETS}/meatball.svg').read().strip())
    with open(f'{HOOKS}/meatball.ts', 'w') as out:
        out.write(
            '// Generated by scripts/build-sprites.py from plugin/assets/meatball.svg: the sprite.\n'
            '// Its root attributes pick the pose: data-fill (normal/full/stuffed), data-mood\n'
            '// (alert/hurt/sleep/busy/testing/pass/fail/deliver/celebrate), data-chomp, data-mouth, data-idle and data-roll.\n'
            f'export const MEATBALL = {json.dumps(svg)}\n\n'
            '// The agents strip: up to four mini meatballs rolling, as many as data-agents (1-4) says.\n'
            f'export const AGENTS = {json.dumps(compact(open(f"{ASSETS}/meatball-agents.svg").read().strip()))}\n'
        )


if __name__ == '__main__':
    big()
    print('built plugin/hooks/meatball.ts')
